export const projects = [
  {
    id: '01',
    slug: 'hacken-dashboard',
    client: 'Hacken (Web3 Security)',
    title: 'Smart Contract Audit Dashboard',
    category: 'Web3 · Dashboard · Next.js',
    desc: "Built an internal audit management platform for Hacken's security team — enabling reviewers to track findings, manage client reports, and generate compliance documentation at scale. Integrated with their existing Web3 toolchain.",
    fullDesc: "Hacken required a high-performance internal tool to streamline their smart contract auditing process. We developed a custom dashboard that allows security engineers to upload contract code, flag vulnerabilities, and automatically generate audit reports in PDF and Markdown formats. The platform includes a real-time collaboration engine and integration with on-chain data to provide context for security findings.",
    tags: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL'],
    bg: 'bg-white border border-border text-fg',
    numColor: 'text-white/10',
    metrics: ['80% faster report generation', '40+ audits processed monthly', 'Zero data leaks'],
  },
  {
    id: '02',
    slug: 'tokwealth-app',
    client: 'Tokwealth',
    title: 'Crypto Portfolio Management App',
    category: 'Fintech · Web App · React',
    desc: 'Designed and developed a Web3 portfolio tracker and wealth management platform — featuring real-time on-chain data, DeFi protocol integrations, and a clean dashboard UI built for retail crypto investors.',
    fullDesc: "Tokwealth aimed to simplify DeFi for the average investor. We built an all-in-one portfolio tracker that connects to multiple wallets and tracks assets across 15+ chains. The application provides advanced analytics on yield farm performance, gas usage history, and tax-ready reporting. We focused on a premium, glassmorphic UI to instill trust and clarity in a complex financial environment.",
    tags: ['React', 'Ethers.js', 'Node.js', 'MongoDB', 'CoinGecko API'],
    bg: 'bg-white border border-border text-fg',
    numColor: 'text-purple/20',
    metrics: ['200k+ tracked wallets', '$50M+ total volume tracked', '4.8 App Store rating'],
  },
  {
    id: '03',
    slug: 'magnetiq-bank-ux',
    client: 'Magnetiq Bank',
    title: 'Fintech Banking Interface',
    category: 'Fintech · UI/UX · SaaS',
    desc: "Redesigned and engineered the client-facing web interface for Magnetiq Bank's business banking product — improving onboarding flows, payments UX, and dashboard performance, resulting in a 40% reduction in support tickets.",
    fullDesc: "Magnetiq Bank needed to modernize their business banking portal to compete with neo-banks. We lead the complete overhaul of their frontend architecture and UI. By implementing a custom design system and optimizing API orchestration, we reduced page load times by 0.8 seconds and significantly lowered user friction in the international wire transfer flow.",
    tags: ['React', 'Figma', 'Node.js', 'REST API', 'Stripe'],
    bg: 'bg-white border border-border text-fg',
    numColor: 'text-chart-2/20',
    metrics: ['40% fewer support tickets', '25% increase in onboarding completion', 'Sub-second dashboard load'],
  },
  {
    id: '04',
    slug: 'smartbike-mobility',
    client: 'SmartBike',
    title: 'Smart Mobility Platform & Admin Dashboard',
    category: 'Mobility · React Native · IoT',
    desc: "Built the rider-facing mobile app and operations admin dashboard for SmartBike's bike-share platform — including real-time GPS tracking, ride session management, payment integration, and fleet analytics.",
    fullDesc: "For SmartBike, we built a comprehensive mobility ecosystem comprising a rider mobile app and a sophisticated ops dashboard. The platform handles thousands of simultaneous sessions, with real-time IoT integration for bike unlocking and heart-beat tracking. The admin tool provides fleet managers with heatmaps of usage, battery health alerts, and automated rebalancing logic.",
    tags: ['React Native', 'Node.js', 'PostgreSQL', 'Google Maps API', 'Stripe'],
    bg: 'bg-surface border border-border text-fg',
    numColor: 'text-subtle/10',
    metrics: ['50k+ active riders', '1200+ bikes managed', '99.99% system uptime'],
  },
];
