export const services = [
  {
    title: 'AI & Machine Learning',
    desc: 'We build AI solutions tailored to your business needs. This includes training machine learning models, using advanced AI tools, and creating smart systems that help you make better decisions and grow your business.',
    type: 'purple',
    tags: ['OpenAI', 'PyTorch', 'TensorFlow', 'LLMs'],
  },
  {
    title: 'Full-Stack Development',
    desc: 'We build complete web applications from backend to frontend. Our focus is on creating fast, scalable, and user-friendly products using modern technologies like React and Next.js.',
    type: 'dark',
    tags: ['React', 'Next.js', 'Node.js', 'PostgreSQL'],
  },
  {
    title: 'Mobile App Development',
    desc: 'We develop mobile apps for Android and iOS, both native and cross-platform. Our apps are smooth, fast, and work well even without internet, with strong performance and native features.',
    type: 'surface',
    tags: ['React Native', 'Swift', 'Kotlin', 'Flutter'],
  },
  {
    title: 'AI Agents & Automation',
    desc: 'We automate business processes using AI agents and tools. This helps reduce manual work, improve efficiency, and allows your team to focus on more important tasks.',
    type: 'purple',
    tags: ['n8n', 'Zapier', 'Python', 'Automation'],
  },
  {
    title: 'Cloud Architecture',
    desc: 'We design and manage cloud systems on AWS, GCP, and Azure. Our solutions are secure, scalable, and cost-efficient, ensuring your applications run smoothly at any scale.',
    type: 'surface',
    tags: ['AWS', 'GCP', 'Azure', 'Terraform'],
  },
  {
    title: 'Enterprise Solutions',
    desc: 'We build large-scale applications for enterprises with strong security, compliance, and scalability. Our systems are designed to handle high traffic and complex business needs.',
    type: 'surface',
    tags: ['Architecture', 'Security', 'Compliance', 'Scalability'],
  },
  {
    title: 'Data Engineering',
    desc: 'We create data systems that collect, process, and organize data efficiently. This helps turn raw data into useful insights for better business decisions.',
    type: 'surface',
    tags: ['Spark', 'Kafka', 'Snowflake', 'ETL'],
  },
  {
    title: 'API Development',
    desc: 'We build secure and fast APIs for your applications using modern standards. Our APIs are reliable, well-documented, and scalable for long-term use.',
    type: 'surface',
    tags: ['GraphQL', 'REST', 'gRPC', 'NestJS'],
  },
  {
    title: 'Staff Augmentation',
    desc: 'We provide skilled developers to support your team quickly. Whether you need experts or a full team, we help you scale without long hiring processes.',
    type: 'surface',
    tags: ['Engineering', 'Leadership', 'Scaling', 'Staffing'],
  },
  {
    title: 'Analytics & BI',
    desc: 'We turn complex data into simple dashboards and reports. This helps you track performance, find problems, and make better business decisions easily.',
    type: 'surface',
    tags: ['SQL', 'PowerBI', 'Tableau', 'Looker'],
  },
  {
    title: 'DevOps & CI/CD',
    desc: 'We improve your development process with automation and continuous deployment. This helps you release updates faster, safely, and with minimal downtime.',
    type: 'purple',
    tags: ['Github Actions', 'Docker', 'Kubernetes', 'CI/CD'],
  },
  {
    title: 'MVP Development',
    desc: 'We help turn your ideas into working products quickly. Using fast development methods, we build MVPs to test your idea and attract early users or investors.',
    type: 'surface',
    tags: ['Prototypes', 'Agile', 'Lean', 'Startup'],
  },
  {
    title: 'Web3 & dApp Development',
    desc: 'We build decentralized applications including smart contracts, frontend interfaces, and wallet integrations. We have experience working with real Web3 clients and platforms.',
    type: 'dark',
    tags: ['Solidity', 'Ethers.js', 'Wagmi', 'Polygon', 'Ethereum'],
  },
];